# Generated by Django 3.1.3 on 2022-02-02 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_portfolio_web_app.model.my_portfolio_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio_web_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentindividualaccount',
            name='authorized_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Autorizados'),
        ),
        migrations.AlterField(
            model_name='bond',
            name='maturity_date',
            field=my_portfolio_web_app.model.my_portfolio_model.CalendarDateField(verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='code',
            field=my_portfolio_web_app.model.my_portfolio_model.UpperCaseCharField(max_length=200, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='financialinstrument',
            name='price_each_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Precio por Cada'),
        ),
        migrations.AlterField(
            model_name='financialinstrumenttenderingpayment',
            name='referenced_financial_instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_portfolio_web_app.financialinstrument', verbose_name='Instrumento Referencia'),
        ),
        migrations.AlterField(
            model_name='investmentindividualaccount',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='investmentportfolio',
            name='individual_accounts',
            field=models.ManyToManyField(to='my_portfolio_web_app.InvestmentIndividualAccount', verbose_name='Cuentas'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ars_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisiones ($)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='broker',
            field=models.CharField(choices=[('IOL', 'IOL'), ('BALANZ', 'BALANZ')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=my_portfolio_web_app.model.my_portfolio_model.CalendarDateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_amount',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='price_unit', to='my_portfolio_web_app.currency', verbose_name='Moneda de Pago'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='usd_commissions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisiones (USD)'),
        ),
    ]
