# Generated by Django 3.1.3 on 2022-02-02 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_portfolio_web_app.model.my_portfolio_model


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio_web_app', '0002_auto_20220202_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegrationConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iol_password', models.CharField(max_length=200, verbose_name='Contraseña IOL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, my_portfolio_web_app.model.my_portfolio_model.MyPortfolioModelBehavior),
        ),
    ]
