# Generated by Django 3.1.3 on 2022-02-02 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_portfolio_web_app', '0003_userintegrationconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentportfolio',
            name='authorized_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Autorizados'),
        ),
    ]
