# Generated by Django 3.1.3 on 2022-02-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_web_app', '0004_investmentportfolio_authorized_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegrationconfiguration',
            name='google_sheet_id',
            field=models.CharField(default='', max_length=255, verbose_name='ID Google Sheet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userintegrationconfiguration',
            name='iol_username',
            field=models.CharField(default='', max_length=200, verbose_name='Usuario IOL'),
            preserve_default=False,
        ),
    ]
