# Generated by Django 3.1.3 on 2022-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_web_app', '0005_auto_20220202_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegrationconfiguration',
            name='iol_password',
            field=models.BinaryField(editable=True, max_length=200, verbose_name='Contraseña IOL'),
        ),
    ]
