# Generated by Django 3.1.3 on 2022-02-06 22:50

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('my_portfolio_web_app', '0006_auto_20220206_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userintegrationconfiguration',
            name='iol_password',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200, verbose_name='Contraseña IOL')),
        ),
    ]
